### ISSUE TITLE
Implement syntax checker for django

### ISSUE THREAD

**Issue by hreiche** [Nikhil1912/Athenaeum#50]
Think [this](https://docs.djangoproject.com/en/4.1/ref/validators/) will be helpful

**Comment by Nikhil1912** [comment]
Is this supposed to be a lint?

**Comment by hreiche** [comment]
This issue refers specifically to the [rubric](https://github.com/txt/se22/blob/main/docs/proj1.md) item "use of syntax checkers." Looking up what a lint is, I think that would probably fulfill the requirement, so yes?
